const countryCodeList = [
  { alpha_2: 'KR', code_ko: '대한민국', code_en: 'Republic of Korea' },
  { alpha_2: 'GH', code_ko: '가나', code_en: 'Ghana' },
  { alpha_2: 'GA', code_ko: '가봉', code_en: 'Gabon' },
  { alpha_2: 'GY', code_ko: '가이아나', code_en: 'Guyana' },
  { alpha_2: 'GM', code_ko: '감비아', code_en: 'Gambia' },
  { alpha_2: 'GG', code_ko: '건지섬', code_en: 'Guernsey' },
  { alpha_2: 'GP', code_ko: '과들루프', code_en: 'Guadeloupe' },
  { alpha_2: 'GT', code_ko: '과테말라', code_en: 'Guatemala' },
  { alpha_2: 'GU', code_ko: '괌', code_en: 'Guam' },
  { alpha_2: 'GD', code_ko: '그레나다', code_en: 'Grenada' },
  { alpha_2: 'GR', code_ko: '그리스', code_en: 'Greece' },
  { alpha_2: 'GL', code_ko: '그린란드', code_en: 'Greenland' },
  { alpha_2: 'GN', code_ko: '기니', code_en: 'Guinea' },
  { alpha_2: 'GW', code_ko: '기니비사우', code_en: 'Guinea-Bissau' },
  { alpha_2: 'NA', code_ko: '나미비아', code_en: 'Namibia' },
  { alpha_2: 'NR', code_ko: '나우루', code_en: 'Nauru' },
  { alpha_2: 'NG', code_ko: '나이지리아', code_en: 'Nigeria' },
  { alpha_2: 'AQ', code_ko: '남극', code_en: 'Antarctica' },
  { alpha_2: 'ZA', code_ko: '남아프리카 공화국', code_en: 'South Africa' },
  { alpha_2: 'NL', code_ko: '네덜란드', code_en: 'Netherlands' },
  { alpha_2: 'AN', code_ko: '네덜란드령 안틸레스', code_en: 'Nederlandse Antillen' },
  { alpha_2: 'NP', code_ko: '네팔', code_en: 'Nepal' },
  { alpha_2: 'NO', code_ko: '노르웨이', code_en: 'Norway' },
  { alpha_2: 'NF', code_ko: '노퍽 섬', code_en: 'Norfuk Ailen' },
  { alpha_2: 'NC', code_ko: '누벨칼레도니', code_en: 'New Caledonia' },
  { alpha_2: 'NZ', code_ko: '뉴질랜드', code_en: 'New Zealand' },
  { alpha_2: 'NU', code_ko: '니우에', code_en: 'Niue' },
  { alpha_2: 'NE', code_ko: '니제르', code_en: 'Niger' },
  { alpha_2: 'NI', code_ko: '니카라과', code_en: 'Nicaragua' },
  { alpha_2: 'DK', code_ko: '덴마크', code_en: 'Danmark' },
  { alpha_2: 'DO', code_ko: '도미니카공화국', code_en: 'Dominican Republic' },
  { alpha_2: 'DM', code_ko: '도미니카 연방', code_en: 'Dominica' },
  { alpha_2: 'DE', code_ko: '독일', code_en: 'Germany' },
  { alpha_2: 'TL', code_ko: '동티모르', code_en: 'East Timor Leste' },
  { alpha_2: 'LA', code_ko: '라오스', code_en: 'Laos' },
  { alpha_2: 'LR', code_ko: '라이베리아', code_en: 'Republic of Liberia' },
  { alpha_2: 'LV', code_ko: '라트비아', code_en: 'Latvija' },
  { alpha_2: 'RU', code_ko: '러시아', code_en: 'Russia' },
  { alpha_2: 'LB', code_ko: '레바논', code_en: 'Lebanon' },
  { alpha_2: 'LS', code_ko: '레소토', code_en: 'Lesotho' },
  { alpha_2: 'RE', code_ko: '레위니옹', code_en: 'Reunion' },
  { alpha_2: 'RO', code_ko: '루마니아', code_en: 'Romania' },
  { alpha_2: 'LU', code_ko: '룩셈부르크', code_en: 'Luxembourg' },
  { alpha_2: 'RW', code_ko: '르완다', code_en: 'Rwanda' },
  { alpha_2: 'LY', code_ko: '리비아', code_en: 'Libya' },
  { alpha_2: 'LT', code_ko: '리투아니아', code_en: 'Lithuania' },
  { alpha_2: 'LI', code_ko: '리히텐슈타인', code_en: 'Liechtenstein' },
  { alpha_2: 'MG', code_ko: '마다가스카르', code_en: 'Madagascar' },
  { alpha_2: 'MQ', code_ko: '마르티니크', code_en: 'Martinique' },
  { alpha_2: 'MH', code_ko: '마셜 제도', code_en: 'Marshall Is.' },
  { alpha_2: 'YT', code_ko: '마요트', code_en: 'Mayotte' },
  { alpha_2: 'MO', code_ko: '마카오', code_en: 'Macau' },
  { alpha_2: 'MK', code_ko: '북마케도니아', code_en: 'North Macedonia' },
  { alpha_2: 'MW', code_ko: '말라위', code_en: 'Malawi' },
  { alpha_2: 'MY', code_ko: '말레이시아', code_en: 'Malaysia' },
  { alpha_2: 'ML', code_ko: '말리', code_en: 'Mali' },
  { alpha_2: 'IM', code_ko: '맨섬', code_en: 'Isle of Man' },
  { alpha_2: 'MX', code_ko: '멕시코', code_en: 'Mexico' },
  { alpha_2: 'MC', code_ko: '모나코', code_en: 'Monaco' },
  { alpha_2: 'MA', code_ko: '모로코', code_en: 'Morocco' },
  { alpha_2: 'MU', code_ko: '모리셔스', code_en: 'Mauritius' },
  { alpha_2: 'MR', code_ko: '모리타니', code_en: 'Mauritania' },
  { alpha_2: 'MZ', code_ko: '모잠비크', code_en: 'Mozambique' },
  { alpha_2: 'ME', code_ko: '몬테네그로', code_en: 'Montenegro' },
  { alpha_2: 'MS', code_ko: '몬트세랫', code_en: 'Montserrat' },
  { alpha_2: 'MD', code_ko: '몰도바', code_en: 'Moldova (the Republic of)' },
  { alpha_2: 'MV', code_ko: '몰디브', code_en: 'Maldives' },
  { alpha_2: 'MT', code_ko: '몰타', code_en: 'Malta' },
  { alpha_2: 'MN', code_ko: '몽골', code_en: 'Mongolia' },
  { alpha_2: 'US', code_ko: '미국', code_en: 'United States of America' },
  { alpha_2: 'UM', code_ko: '미국령 군소 제도', code_en: 'United States Minor Outlying Islands' },
  { alpha_2: 'VI', code_ko: '미국령 버진아일랜드', code_en: 'United States Virgin Islands' },
  { alpha_2: 'MM', code_ko: '미얀마', code_en: 'Republic of the Union of Myanmar' },
  { alpha_2: 'FM', code_ko: '미크로네시아 연방', code_en: 'Micronesia' },
  { alpha_2: 'VU', code_ko: '바누아투', code_en: 'Vanuatu' },
  { alpha_2: 'BH', code_ko: '바레인', code_en: 'Bahrain' },
  { alpha_2: 'BB', code_ko: '바베이도스', code_en: 'Barbados' },
  { alpha_2: 'VA', code_ko: '바티칸 시국', code_en: 'Vatican City' },
  { alpha_2: 'BS', code_ko: '바하마', code_en: 'Bahamas' },
  { alpha_2: 'BD', code_ko: '방글라데시', code_en: 'Bangladesh' },
  { alpha_2: 'BM', code_ko: '버뮤다', code_en: 'Bermuda ls.' },
  { alpha_2: 'BJ', code_ko: '베냉', code_en: 'Benin' },
  { alpha_2: 'VE', code_ko: '베네수엘라', code_en: 'Venezuela (Bolivarian Republic of)' },
  { alpha_2: 'VN', code_ko: '베트남', code_en: 'Viet Nam' },
  { alpha_2: 'BE', code_ko: '벨기에', code_en: 'Belgium' },
  { alpha_2: 'BY', code_ko: '벨라루스', code_en: 'Belarus' },
  { alpha_2: 'BZ', code_ko: '벨리즈', code_en: 'Belize' },
  { alpha_2: 'BA', code_ko: '보스니아 헤르체고비나', code_en: 'Bosnia and Herzegovina' },
  { alpha_2: 'BW', code_ko: '보츠와나', code_en: 'Botswana' },
  { alpha_2: 'BO', code_ko: '볼리비아', code_en: 'Bolivia' },
  { alpha_2: 'BI', code_ko: '부룬디', code_en: 'Burundi' },
  { alpha_2: 'BF', code_ko: '부르키나파소', code_en: 'Burkina Faso' },
  { alpha_2: 'BV', code_ko: '부베섬', code_en: 'Bouvet Island' },
  { alpha_2: 'BT', code_ko: '부탄', code_en: 'Bhutan' },
  { alpha_2: 'MP', code_ko: '북마리아나 제도', code_en: 'Northern Mariana Is.' },
  { alpha_2: 'BG', code_ko: '불가리아', code_en: 'Bulgaria' },
  { alpha_2: 'BR', code_ko: '브라질', code_en: 'Brazil' },
  { alpha_2: 'BN', code_ko: '브루나이', code_en: 'Brunei Darussalam' },
  { alpha_2: 'WS', code_ko: '사모아', code_en: 'Samoa' },
  { alpha_2: 'SA', code_ko: '사우디아라비아', code_en: 'Saudi Arabia' },
  { alpha_2: 'GS', code_ko: '사우스조지아 사우스샌드위치 제도', code_en: 'South Georgia and the South Sandwich Islands' },
  { alpha_2: 'SM', code_ko: '산마리노', code_en: 'San Marino' },
  { alpha_2: 'ST', code_ko: '상투메 프린시페', code_en: 'Sao Tome and Principe' },
  { alpha_2: 'PM', code_ko: '생피에르 미클롱', code_en: 'Saint Pierre and Miquelon' },
  { alpha_2: 'EH', code_ko: '서사하라', code_en: 'Western Sahara' },
  { alpha_2: 'SN', code_ko: '세네갈', code_en: 'Senegal' },
  { alpha_2: 'RS', code_ko: '세르비아', code_en: 'Serbia' },
  { alpha_2: 'SC', code_ko: '세이셸', code_en: 'Seychelles' },
  { alpha_2: 'LS', code_ko: '세인트루시아', code_en: 'Saint Lucia' },
  { alpha_2: 'VC', code_ko: '세인트빈센트 그레나딘', code_en: 'Saint Vincent and the Grenadines' },
  { alpha_2: 'KN', code_ko: '세인트키츠 네비스', code_en: 'Saint Kitts and Nevis' },
  { alpha_2: 'SH', code_ko: '세인트헬레나', code_en: 'Saint Helena, Ascension and Tristan da Cunha' },
  { alpha_2: 'SO', code_ko: '소말리아', code_en: 'Somalia' },
  { alpha_2: 'SB', code_ko: '솔로몬 제도', code_en: 'Solomon Islands' },
  { alpha_2: 'SD', code_ko: '수단', code_en: 'Sudan' },
  { alpha_2: 'SR', code_ko: '수리남', code_en: 'Suriname' },
  { alpha_2: 'LK', code_ko: '스리랑카', code_en: 'Sri Lanka' },
  { alpha_2: 'SJ', code_ko: '스발바르 얀마옌', code_en: 'Svalbard and Jan Mayen' },
  { alpha_2: 'SE', code_ko: '스웨덴', code_en: 'Sweden' },
  { alpha_2: 'CH', code_ko: '스위스', code_en: 'Switzerland' },
  { alpha_2: 'ES', code_ko: '스페인', code_en: 'Spain' },
  { alpha_2: 'SK', code_ko: '슬로바키아', code_en: 'Slovakia' },
  { alpha_2: 'SI', code_ko: '슬로베니아', code_en: 'Slovenia' },
  { alpha_2: 'SY', code_ko: '시리아', code_en: 'Syrian Arab Republic' },
  { alpha_2: 'SL', code_ko: '시에라리온', code_en: 'Sierra Leone' },
  { alpha_2: 'SX', code_ko: '신트마르턴', code_en: 'Sint Maarten' },
  { alpha_2: 'SG', code_ko: '싱가포르', code_en: 'Singapore' },
  { alpha_2: 'AE', code_ko: '아랍에미리트', code_en: 'United Arab Emirates' },
  { alpha_2: 'AW', code_ko: '아루바', code_en: 'Aruba' },
  { alpha_2: 'AM', code_ko: '아르메니아', code_en: 'Armenia' },
  { alpha_2: 'AR', code_ko: '아르헨티나', code_en: 'Argentina' },
  { alpha_2: 'AS', code_ko: '아메리칸사모아', code_en: 'American Samoa' },
  { alpha_2: 'IS', code_ko: '아이슬란드', code_en: 'Iceland' },
  { alpha_2: 'HT', code_ko: '아이티', code_en: 'Haiti' },
  { alpha_2: 'IE', code_ko: '아일랜드', code_en: 'Ireland' },
  { alpha_2: 'AZ', code_ko: '아제르바이잔', code_en: 'Azerbaijan' },
  { alpha_2: 'AF', code_ko: '아프가니스탄', code_en: 'Afghanistan' },
  { alpha_2: 'AD', code_ko: '안도라', code_en: 'Andorra' },
  { alpha_2: 'AL', code_ko: '알바니아', code_en: 'Albania' },
  { alpha_2: 'DZ', code_ko: '알제리', code_en: 'Algeria' },
  { alpha_2: 'AO', code_ko: '앙골라', code_en: 'Angola' },
  { alpha_2: 'AG', code_ko: '앤티가 바부다', code_en: 'Antigua and Barbuda' },
  { alpha_2: 'AI', code_ko: '앵귈라', code_en: 'Anguilla' },
  { alpha_2: 'ER', code_ko: '에리트레아', code_en: 'Eritrea' },
  { alpha_2: 'SZ', code_ko: '에스와티니', code_en: 'Eswatini' },
  { alpha_2: 'EE', code_ko: '에스토니아', code_en: 'Estonia' },
  { alpha_2: 'EC', code_ko: '에콰도르', code_en: 'Ecuador' },
  { alpha_2: 'ET', code_ko: '에티오피아', code_en: 'Ethiopia' },
  { alpha_2: 'SV', code_ko: '엘살바도르', code_en: 'El Salvador' },
  { alpha_2: 'GB', code_ko: '영국', code_en: 'United Kingdom of Great Britain and Northern Ireland' },
  { alpha_2: 'VG', code_ko: '영국령 버진아일랜드', code_en: 'British Virgin Islands' },
  { alpha_2: 'IO', code_ko: '영국령 인도양 지역', code_en: 'British Indian Ocean Territory' },
  { alpha_2: 'YE', code_ko: '예멘', code_en: 'Yemen' },
  { alpha_2: 'OM', code_ko: '오만', code_en: 'Oman' },
  { alpha_2: 'AU', code_ko: '오스트레일리아', code_en: 'Australia' },
  { alpha_2: 'AT', code_ko: '오스트리아', code_en: 'Austria' },
  { alpha_2: 'HN', code_ko: '온두라스', code_en: 'Honduras' },
  { alpha_2: 'AX', code_ko: '올란드 제도', code_en: 'Åland Islands' },
  { alpha_2: 'JO', code_ko: '요르단', code_en: 'Jordan' },
  { alpha_2: 'UG', code_ko: '우간다', code_en: 'Uganda' },
  { alpha_2: 'UY', code_ko: '우르과이', code_en: 'Uruguay' },
  { alpha_2: 'UZ', code_ko: '우즈베키스탄', code_en: 'Uzbekistan' },
  { alpha_2: 'UA', code_ko: '우크라이나', code_en: 'Ukraine' },
  { alpha_2: 'WF', code_ko: '왈리스 퓌튀나', code_en: 'Wallis and Futuna' },
  { alpha_2: 'IQ', code_ko: '이라크', code_en: 'Iraq' },
  { alpha_2: 'IR', code_ko: '이란', code_en: 'Iran (Islamic Republic of)' },
  { alpha_2: 'IL', code_ko: '이스라엘', code_en: 'Israel' },
  { alpha_2: 'EG', code_ko: '이집트', code_en: 'Egypt' },
  { alpha_2: 'IT', code_ko: '이탈리아', code_en: 'Italy' },
  { alpha_2: 'IN', code_ko: '인도', code_en: 'India' },
  { alpha_2: 'ID', code_ko: '인도네시아', code_en: 'Indonesia' },
  { alpha_2: 'JP', code_ko: '일본', code_en: 'Japan' },
  { alpha_2: 'JM', code_ko: '자메이카', code_en: 'Jamaica' },
  { alpha_2: 'ZM', code_ko: '잠비아', code_en: 'Zambia' },
  { alpha_2: 'JE', code_ko: '저지섬', code_en: 'Jersey' },
  { alpha_2: 'GQ', code_ko: '적도 기니', code_en: 'Equatorial Guinea' },
  { alpha_2: 'KP', code_ko: '조선민주주의인민공화국', code_en: "Korea (Democratic People's Republic of)" },
  { alpha_2: 'GE', code_ko: '조지아', code_en: 'Georgia' },
  { alpha_2: 'CN', code_ko: '중국', code_en: 'China' },
  { alpha_2: 'CF', code_ko: '중앙아프리카 공화국', code_en: 'Central African Republic' },
  { alpha_2: 'GI', code_ko: '지부티', code_en: 'Djibouti' },
  { alpha_2: 'GI', code_ko: '지브롤터', code_en: 'Gibraltar' },
  { alpha_2: 'ZW', code_ko: '짐바브웨', code_en: 'Zimbabwe' },
  { alpha_2: 'TD', code_ko: '차드', code_en: 'Chad' },
  { alpha_2: 'CZ', code_ko: '체코', code_en: 'Czechia' },
  { alpha_2: 'CL', code_ko: '칠레', code_en: 'Chile' },
  { alpha_2: 'CM', code_ko: '카메룬', code_en: 'Cameroon' },
  { alpha_2: 'CV', code_ko: '카보베르데', code_en: 'Cabo Verde' },
  { alpha_2: 'KZ', code_ko: '카자흐스탄', code_en: 'Kazakhstan' },
  { alpha_2: 'QA', code_ko: '카타르', code_en: 'Qatar' },
  { alpha_2: 'KH', code_ko: '캄보디아', code_en: 'Cambodia' },
  { alpha_2: 'CA', code_ko: '캐나다', code_en: 'Canada' },
  { alpha_2: 'KE', code_ko: '케냐', code_en: 'Kenya' },
  { alpha_2: 'KY', code_ko: '케이맨 제도', code_en: 'Cayman Islands' },
  { alpha_2: 'KM', code_ko: '코모로', code_en: 'Comoros' },
  { alpha_2: 'CR', code_ko: '코스타리카', code_en: 'Costa Rica' },
  { alpha_2: 'CC', code_ko: '코코스 제도', code_en: 'Cocos (Keeling) Islands' },
  { alpha_2: 'CI', code_ko: '코트디부아르', code_en: "Côte d'Ivoire" },
  { alpha_2: 'CO', code_ko: '콜롬비아', code_en: 'Colombia' },
  { alpha_2: 'CG', code_ko: '콩고 공화국', code_en: 'Congo' },
  { alpha_2: 'CD', code_ko: '콩고 민주 공화국', code_en: 'Congo (the Democratic Republic of the)' },
  { alpha_2: 'CU', code_ko: '쿠바', code_en: 'Cuba' },
  { alpha_2: 'KW', code_ko: '쿠웨이트', code_en: 'Kuwait' },
  { alpha_2: 'CK', code_ko: '쿡 제도', code_en: 'Cook Islands' },
  { alpha_2: 'HR', code_ko: '크로아티아', code_en: 'Croatia' },
  { alpha_2: 'CX', code_ko: '크리스마스 섬', code_en: 'Christmas Island' },
  { alpha_2: 'KG', code_ko: '키르기스스탄', code_en: 'Kyrgyzstan' },
  { alpha_2: 'KI', code_ko: '키리바시', code_en: 'Kiribati' },
  { alpha_2: 'CY', code_ko: '키프로스', code_en: 'Cyprus' },
  { alpha_2: 'TW', code_ko: '타이완', code_en: 'Taiwan' },
  { alpha_2: 'TJ', code_ko: '타지키스탄', code_en: 'Tajikistan' },
  { alpha_2: 'TZ', code_ko: '탄자니아', code_en: 'Tanzania, the United Republic of' },
  { alpha_2: 'TH', code_ko: '태국', code_en: 'Thailand' },
  { alpha_2: 'TC', code_ko: '터크스 케이커스 제도', code_en: 'Turks and Caicos Islands' },
  { alpha_2: 'TR', code_ko: '터키', code_en: 'Turkey' },
  { alpha_2: 'TG', code_ko: '토고', code_en: 'Togo' },
  { alpha_2: 'TK', code_ko: '토켈라우', code_en: 'Tokelau' },
  { alpha_2: 'TO', code_ko: '통가', code_en: 'Tonga' },
  { alpha_2: 'TM', code_ko: '투르크메니스탄', code_en: 'Turkmenistan' },
  { alpha_2: 'TV', code_ko: '투발루', code_en: 'Tuvalu' },
  { alpha_2: 'TN', code_ko: '튀니지', code_en: 'Tunisia' },
  { alpha_2: 'TT', code_ko: '트리니다드 토바고', code_en: 'Trinidad and Tobago' },
  { alpha_2: 'PA', code_ko: '파나마', code_en: 'Panama' },
  { alpha_2: 'PY', code_ko: '파라과이', code_en: 'Paraguay' },
  { alpha_2: 'PK', code_ko: '파키스탄', code_en: 'Pakistan' },
  { alpha_2: 'PG', code_ko: '파푸아뉴기니', code_en: 'Papua New Guinea' },
  { alpha_2: 'PW', code_ko: '팔라우', code_en: 'Palau' },
  { alpha_2: 'PS', code_ko: '팔레스타인', code_en: 'Palestine, State of' },
  { alpha_2: 'FO', code_ko: '페로 제도', code_en: 'Faroe Islands' },
  { alpha_2: 'PE', code_ko: '페루', code_en: 'Peru' },
  { alpha_2: 'PT', code_ko: '포르투갈', code_en: 'Portugal' },
  { alpha_2: 'FK', code_ko: '포클랜드 제도', code_en: 'Falkland Islands (Malvinas)' },
  { alpha_2: 'PL', code_ko: '폴란드', code_en: 'Poland' },
  { alpha_2: 'PR', code_ko: '푸에르토리코', code_en: 'Puerto Rico' },
  { alpha_2: 'FR', code_ko: '프랑스', code_en: 'France' },
  { alpha_2: 'GF', code_ko: '프랑스령 기아나', code_en: 'French Guiana' },
  { alpha_2: 'TF', code_ko: '프랑스령 남방 및 남극', code_en: 'French Southern Territories' },
  { alpha_2: 'PF', code_ko: '프랑스령 폴리네시아', code_en: 'French Polynesia' },
  { alpha_2: 'FJ', code_ko: '피지', code_en: 'Fiji' },
  { alpha_2: 'FI', code_ko: '핀란드', code_en: 'Finland' },
  { alpha_2: 'PH', code_ko: '필리핀', code_en: 'Philippines' },
  { alpha_2: 'PN', code_ko: '핏케언 제도', code_en: 'Pitcairn' },
  { alpha_2: 'HM', code_ko: '허드 맥도널드 제도', code_en: 'Heard Island and McDonald Islands' },
  { alpha_2: 'HU', code_ko: '헝가리', code_en: 'Hungary' },
  { alpha_2: 'HK', code_ko: '홍콩', code_en: 'Hong Kong' },
]

const countryCodeMap = {
  KR: { alpha_2: 'KR', code_ko: '대한민국', code_en: 'Republic of Korea' },
  GH: { alpha_2: 'GH', code_ko: '가나', code_en: 'Ghana' },
  GA: { alpha_2: 'GA', code_ko: '가봉', code_en: 'Gabon' },
  GY: { alpha_2: 'GY', code_ko: '가이아나', code_en: 'Guyana' },
  GM: { alpha_2: 'GM', code_ko: '감비아', code_en: 'Gambia' },
  GG: { alpha_2: 'GG', code_ko: '건지섬', code_en: 'Guernsey' },
  GP: { alpha_2: 'GP', code_ko: '과들루프', code_en: 'Guadeloupe' },
  GT: { alpha_2: 'GT', code_ko: '과테말라', code_en: 'Guatemala' },
  GU: { alpha_2: 'GU', code_ko: '괌', code_en: 'Guam' },
  GD: { alpha_2: 'GD', code_ko: '그레나다', code_en: 'Grenada' },
  GR: { alpha_2: 'GR', code_ko: '그리스', code_en: 'Greece' },
  GL: { alpha_2: 'GL', code_ko: '그린란드', code_en: 'Greenland' },
  GN: { alpha_2: 'GN', code_ko: '기니', code_en: 'Guinea' },
  GW: { alpha_2: 'GW', code_ko: '기니비사우', code_en: 'Guinea-Bissau' },
  NA: { alpha_2: 'NA', code_ko: '나미비아', code_en: 'Namibia' },
  NR: { alpha_2: 'NR', code_ko: '나우루', code_en: 'Nauru' },
  NG: { alpha_2: 'NG', code_ko: '나이지리아', code_en: 'Nigeria' },
  AQ: { alpha_2: 'AQ', code_ko: '남극', code_en: 'Antarctica' },
  ZA: { alpha_2: 'ZA', code_ko: '남아프리카 공화국', code_en: 'South Africa' },
  NL: { alpha_2: 'NL', code_ko: '네덜란드', code_en: 'Netherlands' },
  AN: { alpha_2: 'AN', code_ko: '네덜란드령 안틸레스', code_en: 'Nederlandse Antillen' },
  NP: { alpha_2: 'NP', code_ko: '네팔', code_en: 'Nepal' },
  NO: { alpha_2: 'NO', code_ko: '노르웨이', code_en: 'Norway' },
  NF: { alpha_2: 'NF', code_ko: '노퍽 섬', code_en: 'Norfuk Ailen' },
  NC: { alpha_2: 'NC', code_ko: '누벨칼레도니', code_en: 'New Caledonia' },
  NZ: { alpha_2: 'NZ', code_ko: '뉴질랜드', code_en: 'New Zealand' },
  NU: { alpha_2: 'NU', code_ko: '니우에', code_en: 'Niue' },
  NE: { alpha_2: 'NE', code_ko: '니제르', code_en: 'Niger' },
  NI: { alpha_2: 'NI', code_ko: '니카라과', code_en: 'Nicaragua' },
  DK: { alpha_2: 'DK', code_ko: '덴마크', code_en: 'Danmark' },
  DO: { alpha_2: 'DO', code_ko: '도미니카공화국', code_en: 'Dominican Republic' },
  DM: { alpha_2: 'DM', code_ko: '도미니카 연방', code_en: 'Dominica' },
  DE: { alpha_2: 'DE', code_ko: '독일', code_en: 'Germany' },
  TL: { alpha_2: 'TL', code_ko: '동티모르', code_en: 'East Timor Leste' },
  LA: { alpha_2: 'LA', code_ko: '라오스', code_en: 'Laos' },
  LR: { alpha_2: 'LR', code_ko: '라이베리아', code_en: 'Republic of Liberia' },
  LV: { alpha_2: 'LV', code_ko: '라트비아', code_en: 'Latvija' },
  RU: { alpha_2: 'RU', code_ko: '러시아', code_en: 'Russia' },
  LB: { alpha_2: 'LB', code_ko: '레바논', code_en: 'Lebanon' },
  LS: { alpha_2: 'LS', code_ko: '세인트루시아', code_en: 'Saint Lucia' },
  RE: { alpha_2: 'RE', code_ko: '레위니옹', code_en: 'Reunion' },
  RO: { alpha_2: 'RO', code_ko: '루마니아', code_en: 'Romania' },
  LU: { alpha_2: 'LU', code_ko: '룩셈부르크', code_en: 'Luxembourg' },
  RW: { alpha_2: 'RW', code_ko: '르완다', code_en: 'Rwanda' },
  LY: { alpha_2: 'LY', code_ko: '리비아', code_en: 'Libya' },
  LT: { alpha_2: 'LT', code_ko: '리투아니아', code_en: 'Lithuania' },
  LI: { alpha_2: 'LI', code_ko: '리히텐슈타인', code_en: 'Liechtenstein' },
  MG: { alpha_2: 'MG', code_ko: '마다가스카르', code_en: 'Madagascar' },
  MQ: { alpha_2: 'MQ', code_ko: '마르티니크', code_en: 'Martinique' },
  MH: { alpha_2: 'MH', code_ko: '마셜 제도', code_en: 'Marshall Is.' },
  YT: { alpha_2: 'YT', code_ko: '마요트', code_en: 'Mayotte' },
  MO: { alpha_2: 'MO', code_ko: '마카오', code_en: 'Macau' },
  MK: { alpha_2: 'MK', code_ko: '북마케도니아', code_en: 'North Macedonia' },
  MW: { alpha_2: 'MW', code_ko: '말라위', code_en: 'Malawi' },
  MY: { alpha_2: 'MY', code_ko: '말레이시아', code_en: 'Malaysia' },
  ML: { alpha_2: 'ML', code_ko: '말리', code_en: 'Mali' },
  IM: { alpha_2: 'IM', code_ko: '맨섬', code_en: 'Isle of Man' },
  MX: { alpha_2: 'MX', code_ko: '멕시코', code_en: 'Mexico' },
  MC: { alpha_2: 'MC', code_ko: '모나코', code_en: 'Monaco' },
  MA: { alpha_2: 'MA', code_ko: '모로코', code_en: 'Morocco' },
  MU: { alpha_2: 'MU', code_ko: '모리셔스', code_en: 'Mauritius' },
  MR: { alpha_2: 'MR', code_ko: '모리타니', code_en: 'Mauritania' },
  MZ: { alpha_2: 'MZ', code_ko: '모잠비크', code_en: 'Mozambique' },
  ME: { alpha_2: 'ME', code_ko: '몬테네그로', code_en: 'Montenegro' },
  MS: { alpha_2: 'MS', code_ko: '몬트세랫', code_en: 'Montserrat' },
  MD: { alpha_2: 'MD', code_ko: '몰도바', code_en: 'Moldova (the Republic of)' },
  MV: { alpha_2: 'MV', code_ko: '몰디브', code_en: 'Maldives' },
  MT: { alpha_2: 'MT', code_ko: '몰타', code_en: 'Malta' },
  MN: { alpha_2: 'MN', code_ko: '몽골', code_en: 'Mongolia' },
  US: { alpha_2: 'US', code_ko: '미국', code_en: 'United States of America' },
  UM: { alpha_2: 'UM', code_ko: '미국령 군소 제도', code_en: 'United States Minor Outlying Islands' },
  VI: { alpha_2: 'VI', code_ko: '미국령 버진아일랜드', code_en: 'United States Virgin Islands' },
  MM: { alpha_2: 'MM', code_ko: '미얀마', code_en: 'Republic of the Union of Myanmar' },
  FM: { alpha_2: 'FM', code_ko: '미크로네시아 연방', code_en: 'Micronesia' },
  VU: { alpha_2: 'VU', code_ko: '바누아투', code_en: 'Vanuatu' },
  BH: { alpha_2: 'BH', code_ko: '바레인', code_en: 'Bahrain' },
  BB: { alpha_2: 'BB', code_ko: '바베이도스', code_en: 'Barbados' },
  VA: { alpha_2: 'VA', code_ko: '바티칸 시국', code_en: 'Vatican City' },
  BS: { alpha_2: 'BS', code_ko: '바하마', code_en: 'Bahamas' },
  BD: { alpha_2: 'BD', code_ko: '방글라데시', code_en: 'Bangladesh' },
  BM: { alpha_2: 'BM', code_ko: '버뮤다', code_en: 'Bermuda ls.' },
  BJ: { alpha_2: 'BJ', code_ko: '베냉', code_en: 'Benin' },
  VE: { alpha_2: 'VE', code_ko: '베네수엘라', code_en: 'Venezuela (Bolivarian Republic of)' },
  VN: { alpha_2: 'VN', code_ko: '베트남', code_en: 'Viet Nam' },
  BE: { alpha_2: 'BE', code_ko: '벨기에', code_en: 'Belgium' },
  BY: { alpha_2: 'BY', code_ko: '벨라루스', code_en: 'Belarus' },
  BZ: { alpha_2: 'BZ', code_ko: '벨리즈', code_en: 'Belize' },
  BA: { alpha_2: 'BA', code_ko: '보스니아 헤르체고비나', code_en: 'Bosnia and Herzegovina' },
  BW: { alpha_2: 'BW', code_ko: '보츠와나', code_en: 'Botswana' },
  BO: { alpha_2: 'BO', code_ko: '볼리비아', code_en: 'Bolivia' },
  BI: { alpha_2: 'BI', code_ko: '부룬디', code_en: 'Burundi' },
  BF: { alpha_2: 'BF', code_ko: '부르키나파소', code_en: 'Burkina Faso' },
  BV: { alpha_2: 'BV', code_ko: '부베섬', code_en: 'Bouvet Island' },
  BT: { alpha_2: 'BT', code_ko: '부탄', code_en: 'Bhutan' },
  MP: { alpha_2: 'MP', code_ko: '북마리아나 제도', code_en: 'Northern Mariana Is.' },
  BG: { alpha_2: 'BG', code_ko: '불가리아', code_en: 'Bulgaria' },
  BR: { alpha_2: 'BR', code_ko: '브라질', code_en: 'Brazil' },
  BN: { alpha_2: 'BN', code_ko: '브루나이', code_en: 'Brunei Darussalam' },
  WS: { alpha_2: 'WS', code_ko: '사모아', code_en: 'Samoa' },
  SA: { alpha_2: 'SA', code_ko: '사우디아라비아', code_en: 'Saudi Arabia' },
  GS: { alpha_2: 'GS', code_ko: '사우스조지아 사우스샌드위치 제도', code_en: 'South Georgia and the South Sandwich Islands' },
  SM: { alpha_2: 'SM', code_ko: '산마리노', code_en: 'San Marino' },
  ST: { alpha_2: 'ST', code_ko: '상투메 프린시페', code_en: 'Sao Tome and Principe' },
  PM: { alpha_2: 'PM', code_ko: '생피에르 미클롱', code_en: 'Saint Pierre and Miquelon' },
  EH: { alpha_2: 'EH', code_ko: '서사하라', code_en: 'Western Sahara' },
  SN: { alpha_2: 'SN', code_ko: '세네갈', code_en: 'Senegal' },
  RS: { alpha_2: 'RS', code_ko: '세르비아', code_en: 'Serbia' },
  SC: { alpha_2: 'SC', code_ko: '세이셸', code_en: 'Seychelles' },
  VC: { alpha_2: 'VC', code_ko: '세인트빈센트 그레나딘', code_en: 'Saint Vincent and the Grenadines' },
  KN: { alpha_2: 'KN', code_ko: '세인트키츠 네비스', code_en: 'Saint Kitts and Nevis' },
  SH: { alpha_2: 'SH', code_ko: '세인트헬레나', code_en: 'Saint Helena, Ascension and Tristan da Cunha' },
  SO: { alpha_2: 'SO', code_ko: '소말리아', code_en: 'Somalia' },
  SB: { alpha_2: 'SB', code_ko: '솔로몬 제도', code_en: 'Solomon Islands' },
  SD: { alpha_2: 'SD', code_ko: '수단', code_en: 'Sudan' },
  SR: { alpha_2: 'SR', code_ko: '수리남', code_en: 'Suriname' },
  LK: { alpha_2: 'LK', code_ko: '스리랑카', code_en: 'Sri Lanka' },
  SJ: { alpha_2: 'SJ', code_ko: '스발바르 얀마옌', code_en: 'Svalbard and Jan Mayen' },
  SE: { alpha_2: 'SE', code_ko: '스웨덴', code_en: 'Sweden' },
  CH: { alpha_2: 'CH', code_ko: '스위스', code_en: 'Switzerland' },
  ES: { alpha_2: 'ES', code_ko: '스페인', code_en: 'Spain' },
  SK: { alpha_2: 'SK', code_ko: '슬로바키아', code_en: 'Slovakia' },
  SI: { alpha_2: 'SI', code_ko: '슬로베니아', code_en: 'Slovenia' },
  SY: { alpha_2: 'SY', code_ko: '시리아', code_en: 'Syrian Arab Republic' },
  SL: { alpha_2: 'SL', code_ko: '시에라리온', code_en: 'Sierra Leone' },
  SX: { alpha_2: 'SX', code_ko: '신트마르턴', code_en: 'Sint Maarten' },
  SG: { alpha_2: 'SG', code_ko: '싱가포르', code_en: 'Singapore' },
  AE: { alpha_2: 'AE', code_ko: '아랍에미리트', code_en: 'United Arab Emirates' },
  AW: { alpha_2: 'AW', code_ko: '아루바', code_en: 'Aruba' },
  AM: { alpha_2: 'AM', code_ko: '아르메니아', code_en: 'Armenia' },
  AR: { alpha_2: 'AR', code_ko: '아르헨티나', code_en: 'Argentina' },
  AS: { alpha_2: 'AS', code_ko: '아메리칸사모아', code_en: 'American Samoa' },
  IS: { alpha_2: 'IS', code_ko: '아이슬란드', code_en: 'Iceland' },
  HT: { alpha_2: 'HT', code_ko: '아이티', code_en: 'Haiti' },
  IE: { alpha_2: 'IE', code_ko: '아일랜드', code_en: 'Ireland' },
  AZ: { alpha_2: 'AZ', code_ko: '아제르바이잔', code_en: 'Azerbaijan' },
  AF: { alpha_2: 'AF', code_ko: '아프가니스탄', code_en: 'Afghanistan' },
  AD: { alpha_2: 'AD', code_ko: '안도라', code_en: 'Angola' },
  AL: { alpha_2: 'AL', code_ko: '알바니아', code_en: 'Albania' },
  DZ: { alpha_2: 'DZ', code_ko: '알제리', code_en: 'Algeria' },
  AO: { alpha_2: 'AO', code_ko: '앙골라', code_en: 'Angola' },
  AG: { alpha_2: 'AG', code_ko: '앤티가 바부다', code_en: 'Antigua and Barbuda' },
  AI: { alpha_2: 'AI', code_ko: '앵귈라', code_en: 'Anguilla' },
  ER: { alpha_2: 'ER', code_ko: '에리트레아', code_en: 'Eritrea' },
  SZ: { alpha_2: 'SZ', code_ko: '에스와티니', code_en: 'Eswatini' },
  EE: { alpha_2: 'EE', code_ko: '에스토니아', code_en: 'Estonia' },
  EC: { alpha_2: 'EC', code_ko: '에콰도르', code_en: 'Ecuador' },
  ET: { alpha_2: 'ET', code_ko: '에티오피아', code_en: 'Ethiopia' },
  SV: { alpha_2: 'SV', code_ko: '엘살바도르', code_en: 'El Salvador' },
  GB: { alpha_2: 'GB', code_ko: '영국', code_en: 'United Kingdom of Great Britain and Northern Ireland' },
  VG: { alpha_2: 'VG', code_ko: '영국령 버진아일랜드', code_en: 'British Virgin Islands' },
  IO: { alpha_2: 'IO', code_ko: '영국령 인도양 지역', code_en: 'British Indian Ocean Territory' },
  YE: { alpha_2: 'YE', code_ko: '예멘', code_en: 'Yemen' },
  OM: { alpha_2: 'OM', code_ko: '오만', code_en: 'Oman' },
  AU: { alpha_2: 'AU', code_ko: '오스트레일리아', code_en: 'Australia' },
  AT: { alpha_2: 'AT', code_ko: '오스트리아', code_en: 'Austria' },
  HN: { alpha_2: 'HN', code_ko: '온두라스', code_en: 'Honduras' },
  AX: { alpha_2: 'AX', code_ko: '올란드 제도', code_en: 'Åland Islands' },
  JO: { alpha_2: 'JO', code_ko: '요르단', code_en: 'Jordan' },
  UG: { alpha_2: 'UG', code_ko: '우간다', code_en: 'Uganda' },
  UY: { alpha_2: 'UY', code_ko: '우르과이', code_en: 'Uruguay' },
  UZ: { alpha_2: 'UZ', code_ko: '우즈베키스탄', code_en: 'Uzbekistan' },
  UA: { alpha_2: 'UA', code_ko: '우크라이나', code_en: 'Ukraine' },
  WF: { alpha_2: 'WF', code_ko: '왈리스 퓌튀나', code_en: 'Wallis and Futuna' },
  IQ: { alpha_2: 'IQ', code_ko: '이라크', code_en: 'Iraq' },
  IR: { alpha_2: 'IR', code_ko: '이란', code_en: 'Iran (Islamic Republic of)' },
  IL: { alpha_2: 'IL', code_ko: '이스라엘', code_en: 'Israel' },
  EG: { alpha_2: 'EG', code_ko: '이집트', code_en: 'Egypt' },
  IT: { alpha_2: 'IT', code_ko: '이탈리아', code_en: 'Italy' },
  IN: { alpha_2: 'IN', code_ko: '인도', code_en: 'India' },
  ID: { alpha_2: 'ID', code_ko: '인도네시아', code_en: 'Indonesia' },
  JP: { alpha_2: 'JP', code_ko: '일본', code_en: 'Japan' },
  JM: { alpha_2: 'JM', code_ko: '자메이카', code_en: 'Jamaica' },
  ZM: { alpha_2: 'ZM', code_ko: '잠비아', code_en: 'Zambia' },
  JE: { alpha_2: 'JE', code_ko: '저지섬', code_en: 'Jersey' },
  GQ: { alpha_2: 'GQ', code_ko: '적도 기니', code_en: 'Equatorial Guinea' },
  KP: { alpha_2: 'KP', code_ko: '조선민주주의인민공화국', code_en: "Korea (Democratic People's Republic of)" },
  GE: { alpha_2: 'GE', code_ko: '조지아', code_en: 'Georgia' },
  CN: { alpha_2: 'CN', code_ko: '중국', code_en: 'China' },
  CF: { alpha_2: 'CF', code_ko: '중앙아프리카 공화국', code_en: 'Central African Republic' },
  GI: { alpha_2: 'GI', code_ko: '지브롤터', code_en: 'Gibraltar' },
  ZW: { alpha_2: 'ZW', code_ko: '짐바브웨', code_en: 'Zimbabwe' },
  TD: { alpha_2: 'TD', code_ko: '차드', code_en: 'Chad' },
  CZ: { alpha_2: 'CZ', code_ko: '체코', code_en: 'Czechia' },
  CL: { alpha_2: 'CL', code_ko: '칠레', code_en: 'Chile' },
  CM: { alpha_2: 'CM', code_ko: '카메룬', code_en: 'Cameroon' },
  CV: { alpha_2: 'CV', code_ko: '카보베르데', code_en: 'Cabo Verde' },
  KZ: { alpha_2: 'KZ', code_ko: '카자흐스탄', code_en: 'Kazakhstan' },
  QA: { alpha_2: 'QA', code_ko: '카타르', code_en: 'Qatar' },
  KH: { alpha_2: 'KH', code_ko: '캄보디아', code_en: 'Cambodia' },
  CA: { alpha_2: 'CA', code_ko: '캐나다', code_en: 'Canada' },
  KE: { alpha_2: 'KE', code_ko: '케냐', code_en: 'Kenya' },
  KY: { alpha_2: 'KY', code_ko: '케이맨 제도', code_en: 'Cayman Islands' },
  KM: { alpha_2: 'KM', code_ko: '코모로', code_en: 'Comoros' },
  CR: { alpha_2: 'CR', code_ko: '코스타리카', code_en: 'Costa Rica' },
  CC: { alpha_2: 'CC', code_ko: '코코스 제도', code_en: 'Cocos (Keeling) Islands' },
  CI: { alpha_2: 'CI', code_ko: '코트디부아르', code_en: "Côte d'Ivoire" },
  CO: { alpha_2: 'CO', code_ko: '콜롬비아', code_en: 'Colombia' },
  CG: { alpha_2: 'CG', code_ko: '콩고 공화국', code_en: 'Congo' },
  CD: { alpha_2: 'CD', code_ko: '콩고 민주 공화국', code_en: 'Congo (the Democratic Republic of the)' },
  CU: { alpha_2: 'CU', code_ko: '쿠바', code_en: 'Cuba' },
  KW: { alpha_2: 'KW', code_ko: '쿠웨이트', code_en: 'Kuwait' },
  CK: { alpha_2: 'CK', code_ko: '쿡 제도', code_en: 'Cook Islands' },
  HR: { alpha_2: 'HR', code_ko: '크로아티아', code_en: 'Croatia' },
  CX: { alpha_2: 'CX', code_ko: '크리스마스 섬', code_en: 'Christmas Island' },
  KG: { alpha_2: 'KG', code_ko: '키르기스스탄', code_en: 'Kyrgyzstan' },
  KI: { alpha_2: 'KI', code_ko: '키리바시', code_en: 'Kiribati' },
  CY: { alpha_2: 'CY', code_ko: '키프로스', code_en: 'Cyprus' },
  TW: { alpha_2: 'TW', code_ko: '타이완', code_en: 'Taiwan' },
  TJ: { alpha_2: 'TJ', code_ko: '타지키스탄', code_en: 'Tajikistan' },
  TZ: { alpha_2: 'TZ', code_ko: '탄자니아', code_en: 'Tanzania, the United Republic of' },
  TH: { alpha_2: 'TH', code_ko: '태국', code_en: 'Thailand' },
  TC: { alpha_2: 'TC', code_ko: '터크스 케이커스 제도', code_en: 'Turks and Caicos Islands' },
  TR: { alpha_2: 'TR', code_ko: '터키', code_en: 'Turkey' },
  TG: { alpha_2: 'TG', code_ko: '토고', code_en: 'Togo' },
  TK: { alpha_2: 'TK', code_ko: '토켈라우', code_en: 'Tokelau' },
  TO: { alpha_2: 'TO', code_ko: '통가', code_en: 'Tonga' },
  TM: { alpha_2: 'TM', code_ko: '투르크메니스탄', code_en: 'Turkmenistan' },
  TV: { alpha_2: 'TV', code_ko: '투발루', code_en: 'Tuvalu' },
  TN: { alpha_2: 'TN', code_ko: '튀니지', code_en: 'Tunisia' },
  TT: { alpha_2: 'TT', code_ko: '트리니다드 토바고', code_en: 'Trinidad and Tobago' },
  PA: { alpha_2: 'PA', code_ko: '파나마', code_en: 'Panama' },
  PY: { alpha_2: 'PY', code_ko: '파라과이', code_en: 'Paraguay' },
  PK: { alpha_2: 'PK', code_ko: '파키스탄', code_en: 'Pakistan' },
  PG: { alpha_2: 'PG', code_ko: '파푸아뉴기니', code_en: 'Papua New Guinea' },
  PW: { alpha_2: 'PW', code_ko: '팔라우', code_en: 'Palau' },
  PS: { alpha_2: 'PS', code_ko: '팔레스타인', code_en: 'Palestine, State of' },
  FO: { alpha_2: 'FO', code_ko: '페로 제도', code_en: 'Faroe Islands' },
  PE: { alpha_2: 'PE', code_ko: '페루', code_en: 'Peru' },
  PT: { alpha_2: 'PT', code_ko: '포르투갈', code_en: 'Portugal' },
  FK: { alpha_2: 'FK', code_ko: '포클랜드 제도', code_en: 'Falkland Islands (Malvinas)' },
  PL: { alpha_2: 'PL', code_ko: '폴란드', code_en: 'Poland' },
  PR: { alpha_2: 'PR', code_ko: '푸에르토리코', code_en: 'Puerto Rico' },
  FR: { alpha_2: 'FR', code_ko: '프랑스', code_en: 'France' },
  GF: { alpha_2: 'GF', code_ko: '프랑스령 기아나', code_en: 'French Guiana' },
  TF: { alpha_2: 'TF', code_ko: '프랑스령 남방 및 남극', code_en: 'French Southern Territories' },
  PF: { alpha_2: 'PF', code_ko: '프랑스령 폴리네시아', code_en: 'French Polynesia' },
  FJ: { alpha_2: 'FJ', code_ko: '피지', code_en: 'Fiji' },
  FI: { alpha_2: 'FI', code_ko: '핀란드', code_en: 'Finland' },
  PH: { alpha_2: 'PH', code_ko: '필리핀', code_en: 'Philippines' },
  PN: { alpha_2: 'PN', code_ko: '핏케언 제도', code_en: 'Pitcairn' },
  HM: { alpha_2: 'HM', code_ko: '허드 맥도널드 제도', code_en: 'Heard Island and McDonald Islands' },
  HU: { alpha_2: 'HU', code_ko: '헝가리', code_en: 'Hungary' },
  HK: { alpha_2: 'HK', code_ko: '홍콩', code_en: 'Hong Kong' },
}

const countryData = { countryCodeList, countryCodeMap }
export default countryData
