export const NEXTAUTH_URL = process.env.NEXTAUTH_URL
export const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET
export const KAKAO_CLIENT_ID = process.env.KAKAO_CLIENT_ID
export const KAKAO_CLIENT_SECRET = process.env.KAKAO_CLIENT_SECRET
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
export const FACEBOOK_CLIENT_ID = process.env.FACEBOOK_CLIENT_ID
export const FACEBOOK_CLIENT_SECRET = process.env.FACEBOOK_CLIENT_SECRET
export const DEPLOY_POSITION = process.env.DEPLOY_POSITION || 'local'
